### ISSUE TITLE
Problem with this mod on Fabric Server

### ISSUE THREAD

**Issue by NicolasMKZ** [Ellpeck/PrettyPipes#174]
Hello I wanted to make a server with this mod in 1.18.2 on Fabric and I have a big problem is that it tells me that the forge version is not the right one while all the other mods are working perfectly fine please help me and if possible fix the problem.

Here follows the error I get when I run the server with your mod in it.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install forge, any version.
Unmet dependency listing:
	 - Mod 'prettypipes' (prettypipes) 0.0.0 requires any version of forge, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)

**Comment by Ellpeck** [comment]
Pretty Pipes is not compatible with the Fabric mod loader, it requires Forge.

**Comment by NicolasMKZ** [comment]
And it's not in your plans to make it compatible one day?

**Comment by Ellpeck** [comment]
No, it's not
