### ISSUE TITLE
Failing to load on 1.19.2 when running alongside "SuperMartjn642's Core Lib" (and possible solution)

### ISSUE THREAD

**Issue by remghoost** [Ellpeck/PrettyPipes#210]
Heyo. Recently moved over from 1.12 to 1.19.2 and found your mod.
Super glad it exists (since the "Pipez" mod doesn't show items passing through and itemducts don't seem to be implemented in Thermal Expansion yet).

---

**I noticed that your mod was causing Minecraft to crash while loading when running alongside "SuperMartjn642's Core Lib".**
Here's the error it was throwing:

```
Exception in thread "main" java.lang.module.ResolutionException: Modules jgrapht.core and prettypipes export package org.jgrapht.alg.util to module supermartijn642corelib
at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
at java.base/java.lang.module.Resolver.finish(Unknown Source)
at java.base/java.lang.module.Configuration.<init>(Unknown Source)
at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```
---

**After some digging with ChatGPT, we seem to have found a solution.**

Adjusting the `embed` line to `implementation` in `build.gradle` seems to fix the issue.

https://github.com/Ellpeck/PrettyPipes/blob/c2b2204696448defeb3e7fcea4687ee75378dd7d/build.gradle#L107C1-L109C43

---

**The project now builds correctly, Minecraft now loads correctly, and the pipes seem to be working properly in my test world.**

I'm just getting started using the mod, so I'm not entirely aware of all of the intricacies yet, so I don't wait to claim this as "fixed", but I'm guessing switching that line of code _seems_ to have fixed it.

---

I know you haven't updated the 1.19 branch in a few years now, but I figured I'd bring this to your attention nonetheless.
I didn't make a pull request since I'm not sure this 100% works yet, but it seems to be going fine so far.

I'm a python developer (with _very minimal_ java experience), so I'm not entirely sure of the tradeoffs between `embed` and `implementation`, but yeah.

**Might be worth updating this since a lot of mods in 1.19.2 seem to use "SuperMartjn642's Core Lib".
I'll report back if there are any issues once I actually start using the mod in-game.**

Anyways, thanks for the mod! 
Keep on being awesome. <3

**Comment by remghoost** [comment]
Okay, so this produced its own set of errors, apparently (as tends to happen with programming).

And after removing another mod (Dimensional Doors), your mod seems to load in fine now (unmodified).
Even though it has nothing to do with the offending libraries in the crash log....?

Not sure. I'll mark this as closed.
Please don't mind my 2AM musings.
