### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by PfefferT** [Ellpeck/PrettyPipes#3]
I've figured out an issue with items and I want to fix it to myself and provide a bugfix for you, but I cannot compile it or I don't know how to compile it correctly. I am using the default mdk for 31.1.0 of forge and integrated the code inside of the src/java/main folder with adjusting the dependencies, but it does not work. The build process crashes with:

`[30Apr2020 00:00:39.190] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.1.0 Initialized
[30Apr2020 00:00:40.795] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: net.minecraft.block.Block$Properties.notSolid()Lnet/minecraft/block/Block$Properties;
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class de.ellpeck.prettypipes.Registry registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class de.ellpeck.prettypipes.Registry registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class de.ellpeck.prettypipes.Registry registerTiles(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class de.ellpeck.prettypipes.Registry registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class de.ellpeck.prettypipes.Registry registerContainers(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoSuchMethodError: net.minecraft.block.Block$Properties.notSolid()Lnet/minecraft/block/Block$Properties;
	at de.ellpeck.prettypipes.pipe.PipeBlock.<init>(PipeBlock.java:60)
	at de.ellpeck.prettypipes.Registry.registerBlocks(Registry.java:88)
	at net.minecraftforge.eventbus.ASMEventHandler_2_Registry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:969)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(Main.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:102)
`

**Comment by Ellpeck** [comment]
You don't need to use "the default MDK", all gradle files are already in this repository. You build the mod like any other. Look up a tutorial online.
